name: Postman test cases

on: [push]

jobs:
  apiTests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18"
        cache: 'npm'
    
    - name: install newman
      run: npm i newman 
    
    - name: run test
      run: newman run postman_tests/Books.postman_collection.json -e postman_tests/test.postman_environment.json  



        